# Generated by Django 3.2.4 on 2021-07-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
