# Generated by Django 3.2.4 on 2021-07-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_reviewmodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='useful_review_record',
            new_name='fastest_delivery',
        ),
    ]
