# Generated by Django 3.2.4 on 2021-07-06 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0007_remove_shoppingcartmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewpost.reviewmodel'),
        ),
    ]
