# Generated by Django 3.2.4 on 2021-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0008_shoppingcartmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
