# Generated by Django 3.2.4 on 2021-07-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0011_browsinghistorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowsingHistoryModel',
        ),
    ]
