# Generated by Django 3.2.4 on 2021-07-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0013_browsinghistorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseHistoryModel',
        ),
    ]
